###
GET http://localhost:3000/users/
Content-Type: application/json

###
GET http://localhost:3000/users/3
Content-Type: application/json

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "name" : "fai",
    "email" : "fai@gmail.com"
}

###
PUT  http://localhost:3000/users/2
Content-Type: application/json

{
    "name" : "milfa",
    "email" : "milfa@gmail.com"
}

###
DELETE  http://localhost:3000/users/3
Content-Type: application/json

###
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "milfa@gmail.com",
    "name" : "aulia",
    "password" : "milfa123"
}

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "aulia@gmail.com",
    "password" : "aulia123"
}